<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.apache.openwhisk.core.controller.test.RateThrottleTests" tests="2" skipped="0" failures="0" errors="0" timestamp="2022-12-06T13:11:52" hostname="MacBook-Pro.local" time="60.01">
  <properties/>
  <testcase name="Rate Throttle should throttle when rate exceeds allowed threshold" classname="org.apache.openwhisk.core.controller.test.RateThrottleTests" time="60.007"/>
  <testcase name="Rate Throttle should check against an alternative limit if passed in" classname="org.apache.openwhisk.core.controller.test.RateThrottleTests" time="0.003"/>
  <system-out><![CDATA[[2022-12-06T21:11:52.358Z] [INFO] Shutting down remote daemon.
[2022-12-06T21:11:52.358Z] [INFO] Remote daemon shut down; proceeding with flushing remote transports.
[2022-12-06T21:11:52.359Z] [INFO] Remoting shut down.
[2022-12-06T21:12:07.119Z] [ERROR] Background operation retry gave up
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:102)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkBackgroundRetry(CuratorFrameworkImpl.java:831)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:960)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(CuratorFrameworkImpl.java:912)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$300(CuratorFrameworkImpl.java:70)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl$4.call(CuratorFrameworkImpl.java:316)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
[2022-12-06T21:12:07.120Z] [ERROR] Background retry gave up
org.apache.curator.CuratorConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:941)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(CuratorFrameworkImpl.java:912)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$300(CuratorFrameworkImpl.java:70)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl$4.call(CuratorFrameworkImpl.java:316)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
